### ISSUE TITLE
Ignore detachment of launch clamps

### ISSUE THREAD

**Issue by Gordon-Dry** [jrodrigv/DestructionEffects#11]
When the vessel is ascending, the effect is still active where the launch clamps were attached to when it's several hundred meters in altitude...
It looks like there are holes in the hull of the tank, leaking fuel which burns slowly.

**Comment by gomker** [comment]
Hey Gordon,
There was a feature added to let the user add part names to ignore.

https://github.com/jrodrigv/DestructionEffects/blob/master/Distribution/GameData/DestructionEffects/settings.cfg

Look for the `settings.cfg` and add the name, or part of the name in this config and see if it ignores the clamps.

Regards,

**Comment by Gordon-Dry** [comment]
I will do.
