### ISSUE TITLE
Effects Start Without any Damage

### ISSUE THREAD

**Issue by Sandrik1** [jrodrigv/DestructionEffects#14]
I was playing KSP and a tank that I built in it started to go up in fire and smoke even though I didnt do anything. Is this because of modded parts, and if so can I fix it?

**Comment by jrodrigv** [comment]
Most likely. You can help to fix this issue creating a fork and adding to this list https://github.com/jrodrigv/DestructionEffects/blob/master/Distribution/GameData/DestructionEffects/settings.cfg

The parts id that are triggering the effects. I will then create new release with this changes

**Comment by Sandrik1** [comment]
For some reason now anything I spawn starts emmiting effects. I mean everything! WHY IS THIS HAPPENING!

**Comment by jrodrigv** [comment]
Thats strange. I recommend reinstalling the mod

**Comment by Sandrik1** [comment]
Ok thanks now my craft work it is just some craft that use EXTREME part clipping that don't for some reason.
