### ISSUE TITLE
Smoke should rise up?

### ISSUE THREAD

**Issue by ghost** [jrodrigv/DestructionEffects#15]
Could you make the FX rise up a bit? When the FX is all bunched up together when you have a tank battle, it causes lag, and it also doesn't look nice.

Also, could you decrease the size of the smoke? It's kinda big for one joint broken.

**Comment by ghost** [comment]
Any news?

**Comment by jrodrigv** [comment]
Hi @MuricanJeb I'm not working on this at the moment

**Comment by ghost** [comment]
*cough*
It's been kinda long, are you ready to look into this now @jrodrigv or do you need more time?

**Comment by ghost** [comment]
bump

**Comment by ghost** [comment]
another bump..?

**Comment by MuricanJeb** [comment]
closing since this hasn't been replied to for 1 year :(
