### ISSUE TITLE
Comma in the GitHub version number of the latest release

### ISSUE THREAD

**Issue by HebaruSan** [jrodrigv/DestructionEffects#17]
![image](https://user-images.githubusercontent.com/1559108/38513593-407d1f70-3c1e-11e8-8b1d-bb8c759ecbda.png)

See KSP-CKAN/CKAN#2401 for why anyone would care.

**Comment by jrodrigv** [comment]
Thanks for letting me know :) I will update the tag.

**Comment by jrodrigv** [comment]
fixed
