### ISSUE TITLE
Command seat produces unwanted FX

### ISSUE THREAD

**Issue by SpannerMonkey** [jrodrigv/DestructionEffects#2]
When launching a vehicle with cmd seat extraneous flame and smoke FX are produced this occurs at every scene change , If you have several vehicles with cmd seats switching between them causes every seat to erupt flames and smoke,
Not sure if this is due to the new Kerbals being parts or the actual cmd seat, will be investigating further

**Comment by jrodrigv** [comment]
@SpannerMonkey  Can you try to reproduce the issue again using the dll I just committed?

I have tried to reproduce it but  command seats are working fine for me (even with Kerbals using Take Command )

**Comment by SpannerMonkey** [comment]
will do , I too was using TK

**Comment by SpannerMonkey** [comment]
Hi all checks out fine, occasional instances but much better.  Seats fitted since the fix are clear but some fitted before still produce FX, i feel this is due to the mounting of the unit and KSP method of destruction on scene change, rather than a direct result of some plugin issue, Will close. Thanks
