### ISSUE TITLE
Huge FPS Drop, FX when not needed, FX staying stationary or completely offset

### ISSUE THREAD

**Issue by RagingGamer** [jrodrigv/DestructionEffects#5]
FPS drop only happens if I carpet bomb, it also persists until the effect dies off.

For the bombs, Aviators Arsenal, Kerbin Navy, SM_Armory, and NKD all cause the DFX when releasing the bombs.

As for the FX staying stationary or being offset I offer a screenshot.I grabbed this a little late after I realized I should have it. So it's faint, but near the first bend by the ocean you'll see it.
![desktop 04 04 2017 - 00 09 06 09](https://cloud.githubusercontent.com/assets/23273678/24643438/39b86478-18cb-11e7-98ea-e571b099f611.png)

**Comment by ghost** [comment]
The workarounnd for this problem is to use the BDA missle mounts or Aviator Arsenals bomb holder thing.

**Comment by jrodrigv** [comment]
Thanks @RagingGamer,  there are two diferent issues:

- For the staying stationary or completely offset. At the moment there is no fix for that - BDArmory it self is also suffering from this issue.
-For the bomb triggering destruction effects we can find a solution.

**Comment by RagingGamer** [comment]
@MuricanJeb I'll see if that does fix it. That may, in fact, be why BDA bombs didn't make the effect lol

@jrodrigv Ah, I see. I shoulda figured the same thing that affected BDA was affecting DFX.
As for the bombs, I think MuricanJeb was right. Simple workaround.

**Comment by jrodrigv** [comment]
BTW yesterday I did a new release. It fix the stationary effect problem.

**Comment by RagingGamer** [comment]
Yeah, I just got around to trying it out.  Worked perfectly after doing MuricanJeb's suggestion. Hopefully the same fix can be applied to BDA too? Anyways, good work!
