### ISSUE TITLE
New Texture overhaul by me!

### ISSUE THREAD

**Issue by ghost** [jrodrigv/DestructionEffects#7]
Ok, this is the second time I'm trying this, and I'll leave it up a bit longer.
So, I finally made new FX from the legacy FX and made an IL-2-ish kind of fire.
Heres what it looks like:
![image](https://cloud.githubusercontent.com/assets/22109449/25065147/e788db92-21c6-11e7-8b17-aabd4592b0b4.png)

![image](https://cloud.githubusercontent.com/assets/22109449/25065152/f97e11c8-21c6-11e7-92c4-bdbe18196492.png)

![image](https://cloud.githubusercontent.com/assets/22109449/25065154/1a6a4474-21c7-11e7-862d-12d93cec3631.png)

![image](https://cloud.githubusercontent.com/assets/22109449/25065157/34b42516-21c7-11e7-9dbc-cb032d5a9b30.png)

So, with @jrodrigv's premission and thoughts of the effect, I can release it. So what do you guys think?

**Comment by jrodrigv** [comment]
Can you attach the textures? I will try them.

**Comment by ghost** [comment]
Do you mean as in attaching the files with a comment?

**Comment by jrodrigv** [comment]
You drag & drop a zip file here with you modified version of DFX

**Comment by ghost** [comment]
Alright, here you go!
[DestructionFXmodified.zip](https://github.com/jrodrigv/DestructionEffects/files/923768/DestructionFXmodified.zip)
Enjoy 😄

**Comment by ghost** [comment]
Did you test it yet? It has been 5 hours since you replied.

**Comment by jrodrigv** [comment]
Ni mate, I'll let you know

**Comment by ghost** [comment]
It's been 2 days.
Are you gonna test it now?

**Comment by jrodrigv** [comment]
Nope! I hope to have time during this week :)

**Comment by ghost** [comment]
Should I show this to the whole BDA team via the BDA forum?

**Comment by jrodrigv** [comment]
Sounds like a nice idea, maybe you can record a video?

BTW you should take a look into this http://forum.kerbalspaceprogram.com/index.php?/topic/159613-tkol-the-king-of-laythe-challenge-bdarmory-3vs3-ai-duels-sci-fi-future-weapons-inception-phase/&_fromLogin=1

**Comment by ghost** [comment]
I can't really record a video, mostly because I don't know how :/

I'll check out the link though 👍

**Comment by jrodrigv** [comment]
I really recommend OBS, it is free and there are tutorials on YouTube

El 30 abr. 2017 18:14, "Murican_Jeb" <notifications@github.com> escribió:

I can't really record a video, mostly because I don't know how :/

I'll check out the link though 👍

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jrodrigv/DestructionEffects/issues/7#issuecomment-298241284>,
or mute the thread

**Comment by ghost** [comment]
Any news?

**Comment by jrodrigv** [comment]
Sorry mate, I'm quite busy with other things.

I've taking a look to the textures and I'm not really sure that if they fit
better that the stock ones...

2017-05-06 20:48 GMT+02:00 Murican_Jeb <notifications@github.com>:

**Comment by ghost** [comment]
So we won't use them?

**Comment by MuricanJeb** [comment]
Well, I guess no one really like these textures, so I'll just close the issue 😞
