### ISSUE TITLE
Ignore part detachment by KAS

### ISSUE THREAD

**Issue by gomker** [jrodrigv/DestructionEffects#9]
When detaching parts with KAS wrenches destruction effects is triggered. There should be an event we can key off of to prevent triggering. I will investigate

**Comment by frenchmarrow** [comment]
This is happening to me in 1.7 with most recent updates of affected mods. Any part detachment causes destruction effects. Is there a way to reduce it? Or to have low-speed changes only detach and not cause a fire?
